#!/bin/bash

CURRENT_DIR=$PWD
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "$DIR"

usage() {
    printf "must provide command to add. Ex. $(basename $0) [command to add to lolcat aliases]\n"
}

. ./configs
. ./functions

if [ "$1" == "" ] 
then
	usage
  	exit 1
fi

check_install
check_commands

COM_FILE=$LOLCATCATHOME/commands

OLDIFS=$IFS;
IFS=$'\n'
LOADED=0
while read com; do
	if [ "$com" = $1 ]; 
	then
		LOADED=1
		break
	fi
done <$COM_FILE
IFS=$OLDIFS

if [ $LOADED = "0" ] 
then
	echo $1 | xargs >> $COM_FILE
	echo "Added $1 to lolcatcat"
else
	die "Command already loaded"
fi

cd $CURRENT_DIR
